# Generated by Django 3.1.5 on 2021-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='author_director_draw',
            field=models.CharField(blank=True, db_column='Author_Director_Draw', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_finished',
            field=models.DateField(blank=True, db_column='Date_Finished', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, db_column='Genre', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='medium',
            field=models.CharField(blank=True, db_column='Medium', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(blank=True, db_column='Rating', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='recommend',
            field=models.CharField(blank=True, db_column='Recommend', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='recommended_by',
            field=models.CharField(blank=True, db_column='Recommended_by', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(blank=True, db_column='Review', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='runtime',
            field=models.IntegerField(blank=True, db_column='Runtime', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='synopsis',
            field=models.TextField(blank=True, db_column='Synopsis', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='times_watched',
            field=models.SmallIntegerField(blank=True, db_column='Times_Watched', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year_made',
            field=models.IntegerField(blank=True, db_column='Year_made', null=True),
        ),
    ]
