# Generated by Django 3.0 on 2021-04-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210417_1920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Media',
        ),
    ]
